on:
  pull_request:
    types: [opened, synchronize]

jobs:
  stylelint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: '12'
      - name: Stylelint
        uses: betrybe/stylelint-linter-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  evaluator_job:
    runs-on: ubuntu-18.04
    name: Evaluator job
    steps:
      - uses: actions/checkout@v2
      - name: Cypress evaluator step
        id: cypress
        uses: betrybe/custom-evaluator-action@v5
        with:
          repository-test-name: 'betrybe/sd-0x-project-trybewarts-tests'
          repository-test-branch: 'branch-teste'
        - name: Store evaluation step
          uses: betrybe/store-evaluation-action@v2
        with:
          evaluation-data: ${{ steps.evaluator.outputs.result }}
          environment: staging
          pr-number: ${{ steps.cypress.outputs.pr-number }}
